[package]
name = "envault"
description = "Local-first encrypted secret vault for developers and AI agents"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
default-run = "envault"

[dependencies]
base64.workspace = true
clap.workspace = true
clap_complete = { workspace = true, optional = true }
comfy-table.workspace = true
crossterm.workspace = true
envault-core = { version = "=0.1.1", path = "../envault-core" }
envault-crypto = { version = "=0.1.1", path = "../envault-crypto" }
envault-platform = { version = "=0.1.1", path = "../envault-platform" }
envault-protocol = { version = "=0.1.1", path = "../envault-protocol" }
envault-service = { version = "=0.1.1", path = "../envault-service" }
keyring.workspace = true
ratatui.workspace = true
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
zeroize.workspace = true

[features]
internal-completions = ["dep:clap_complete"]

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(windows)'.dependencies]
envault-windows-ffi = { version = "=0.1.1", path = "../envault-windows-ffi" }

[dev-dependencies]
tempfile.workspace = true
toml.workspace = true

[lints]
workspace = true

[[bin]]
name = "envault"
path = "src/main.rs"

[[bin]]
name = "envaultd"
path = "src/bin/envaultd.rs"

[[bin]]
name = "envaultui"
path = "src/bin/envaultui.rs"
