[package]
name = "envault-store"
description = "Transactional encrypted SQLite persistence for EnVault"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
envault-core = { version = "=0.1.1", path = "../envault-core" }
rusqlite.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
blake3.workspace = true
tempfile.workspace = true

[lints]
workspace = true
