[package]
name = "envault-protocol"
description = "Versioned bounded CBOR IPC protocol for EnVault"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ciborium.workspace = true
envault-core = { version = "=0.0.1", path = "../envault-core" }
envault-policy = { version = "=0.0.1", path = "../envault-policy" }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
zeroize.workspace = true

[lints]
workspace = true
